#!/usr/bin/env python3
"""Sheets -> Java. Each sheet becomes a record type; each row becomes one constant built from that row's columns.

usage: gen.py <java-out> [<resources-out>]
  java:      <java-out>/fail/holocraft/sheet/*.java (one record per sheet, one constant per row) + HoloRefs.java
  resources: item model + item definition JSON for every idol/item row, and en_us.json names
"""
import glob, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(sys.argv[1], "fail", "holocraft", "sheet")
os.makedirs(out, exist_ok=True)

def camel(s, upper=True):
    parts = re.split(r"[^A-Za-z0-9]+", s)
    c = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return c if upper else c[:1].lower() + c[1:]

def jtype(spec):
    t = spec.split(";")[0].strip()
    return {"int": "int", "float": "float", "bool": "boolean"}.get(t, "String")

def jval(v, t):
    if t == "int": return str(int(v))
    if t == "float": return repr(float(v)) + "f"
    if t == "boolean": return "true" if v else "false"
    return json.dumps(v, ensure_ascii=False)

for p in sorted(glob.glob(os.path.join(ROOT, "sheets", "*.json"))):
    s = json.load(open(p))
    rec = camel(s["sheet"]) + "Row"
    cols = list(s["columns"].items())
    fields = ", ".join(f"{jtype(spec)} {camel(c, False)}" for c, spec in cols)
    lines = [
        "// GENERATED from sheets/%s.json by tools/gen.py. Edit the sheet, not this file." % s["sheet"],
        "package fail.holocraft.sheet;", "", "import java.util.List;", "",
        f"public record {rec}({fields}) {{",
    ]
    names = []
    for i, r in enumerate(s["rows"]):
        key = r.get("id") or r.get("event") or r.get("mc_path") or f"level_{r.get('level', i)}"
        const = re.sub(r"[^A-Za-z0-9]+", "_", str(key)).strip("_").upper()
        if const[0].isdigit(): const = "_" + const
        names.append(const)
        args = ", ".join(jval(r[c], jtype(spec)) for c, spec in cols)
        lines.append(f"    public static final {rec} {const} = new {rec}({args});")
    lines.append(f"    public static final List<{rec}> ALL = List.of({', '.join(names)});")
    lines.append("}")
    open(os.path.join(out, rec + ".java"), "w").write("\n".join(lines) + "\n")
# Every HoloCure asset any sheet references, so the importer extracts exactly what the sheets use.
refs = {"holocure sprite": set(), "holocure sound": set(), "holocure string": set(), "holocure font": set(), "holocure object": set(), "holocure room": set()}
all_sheets = {}
for p in sorted(glob.glob(os.path.join(ROOT, "sheets", "*.json"))):
    s = json.load(open(p))
    all_sheets[s["sheet"]] = s
    for c, spec in s["columns"].items():
        t = spec.split(";")[0].strip()
        if t in refs:
            refs[t] |= {r[c] for r in s["rows"]}
def jlist(xs): return ", ".join(json.dumps(x, ensure_ascii=False) for x in sorted(xs))
open(os.path.join(out, "HoloRefs.java"), "w").write(
    "// GENERATED by tools/gen.py from every 'holocure ...' column in sheets/.\n"
    "package fail.holocraft.sheet;\n\nimport java.util.List;\n\npublic final class HoloRefs {\n"
    f"    public static final List<String> SPRITES = List.of({jlist(refs['holocure sprite'])});\n"
    f"    public static final List<String> SOUNDS = List.of({jlist(refs['holocure sound'])});\n"
    f"    public static final List<String> FONTS = List.of({jlist(refs['holocure font'])});\n"
    f"    public static final List<String> STRINGS = List.of({jlist(refs['holocure string'])});\n"
    "    private HoloRefs() {}\n}\n")

if len(sys.argv) > 2:
    res = os.path.join(sys.argv[2], "assets", "holocraft")
    items = [("idol_" + r["id"], r["display"]) for r in all_sheets["idols"]["rows"]] + \
            [(r["id"], r["display"]) for r in all_sheets["items"]["rows"]]
    lang = {}
    for iid, name in items:
        os.makedirs(os.path.join(res, "models", "item"), exist_ok=True)
        os.makedirs(os.path.join(res, "items"), exist_ok=True)
        model = {"parent": "minecraft:item/generated", "textures": {"layer0": f"holocraft:item/{iid}"}}
        if iid.startswith("idol_"):
            # an idol is a portrait card, held small so it does not fill the screen
            model["display"] = {
                "firstperson_righthand": {"rotation": [0, -90, 25], "translation": [1.13, 3.2, 1.13], "scale": [0.38, 0.38, 0.38]},
                "firstperson_lefthand": {"rotation": [0, 90, -25], "translation": [1.13, 3.2, 1.13], "scale": [0.38, 0.38, 0.38]},
                "thirdperson_righthand": {"rotation": [0, 0, 0], "translation": [0, 3, 1], "scale": [0.45, 0.45, 0.45]}}
        json.dump(model,
                  open(os.path.join(res, "models", "item", iid + ".json"), "w"))
        json.dump({"model": {"type": "minecraft:model", "model": f"holocraft:item/{iid}"}},
                  open(os.path.join(res, "items", iid + ".json"), "w"))
        lang[f"item.holocraft.{iid}"] = name
    for r in all_sheets["fans"]["rows"] + all_sheets["bosses"]["rows"]:
        lang[f"entity.holocraft.{r['id']}"] = r["display"]
    data = os.path.join(sys.argv[2], "data", "holocraft", "loot_table", "blocks")
    os.makedirs(data, exist_ok=True)
    def loot(bid):
        json.dump({"type": "minecraft:block", "pools": [{"rolls": 1, "entries": [{"type": "minecraft:item", "name": f"holocraft:{bid}"}],
                   "conditions": [{"condition": "minecraft:survives_explosion"}]}]}, open(os.path.join(data, bid + ".json"), "w"))
    for r in all_sheets["stages"]["rows"]:
        loot(r["id"] + "_ground")
        lang[f"block.holocraft.{r['id']}_ground"] = r["display"].split(" (")[0] + " Ground"
        lang[f"generator.holocraft.{r['id']}"] = r["world_type"]
        lang[f"biome.holocraft.{r['id']}"] = r["display"].split(" (")[0]
    for r in all_sheets["props"]["rows"]:
        loot("prop_" + r["id"])
        lang[f"block.holocraft.prop_{r['id']}"] = r["id"].replace("_", " ").title()
    os.makedirs(os.path.join(res, "lang"), exist_ok=True)
    extra = os.path.join(ROOT, "mod", "src", "main", "lang_extra_en_us.json")
    if os.path.exists(extra):
        lang.update(json.load(open(extra)))
    json.dump(lang, open(os.path.join(res, "lang", "en_us.json"), "w"), indent=1, ensure_ascii=False)
print("generated", out)
